remote_theme: bitbrain/jekyll-dash
# required by disqus to display comments
url: https://julioarruda.com
title: 'Julio Arruda'
description: "GitHub, Azure DevOps e afins"

# jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num/"

# jekyll-tagging (optional)
tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

dash:
  title: Julio Arruda 
  date_format: "%b %-d, %Y"
  show_author: true

  disqus:
    shortname: <your-disqus-shortname>

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/julioarrudac
      icon: twitter-square
      color: cyan
    - url: https://youtube.com/user/julioarrudac
      icon: youtube-square
      color: red
    - url: https://github.com/julioarruda
      icon: github-square
      color: purple
      
  show_author: true

# Replaces the default avatar provider (gravatar)
avatar_source: github
github_username: julioarruda
