# auto generated by stealinator.py
import datetime
import pytz
import os
CWD = os.getcwd()
current_location = os.path.abspath(__file__)
os.chdir(os.path.dirname(current_location))
file = open("last-update.html", "w")
print("<!--autogenerated by last-update.py -->", end="\n\n", file=file)
print("<h5> Last Updated on ", end="", file=file)
print(datetime.datetime.now(pytz.timezone('Asia/Kolkata')).strftime("%m/%d/%Y, %H:%M"), file=file, end="")
print("  IST </h5>", file=file)
print("<h5> Last Updated on ", end="", file=file)
print(datetime.datetime.now(pytz.timezone('UTC')).strftime("%m/%d/%Y, %H:%M"), file=file, end="")
print("  UTC </h5>", file=file)
file.close()
os.chdir(CWD)
print("updated file {} sucessfully".format(file.name))
