# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1
        
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - run: bundle exec jekyll build

      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
        with:
          dir: _site
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
